# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job1 Hello"
  job2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job2 Hello"
  job3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job3 Hello"
  job4:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job4 Hello"
  job5:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job5 Hello"

workflows:
  version: 2
  workflow1:
    jobs: #All jobs will be executed simultaneously
      - job1
      - job2
      - job3
      - job4
  workflow2: #Sequential job execution example
    jobs:
      - job1
      - job2:
          requires:
            - job1
      - job3:
          requires:
            - job2
      - job4:
          requires:
            - job3
  workflow3: #Fan-out/fan-in workflow example
    jobs:
      - job1
      - job2:
          requires:
            - job1
      - job3:
          requires:
            - job1
      - job4:
          requires:
            - job2
            - job3
  workflow4: #Manual approval required
    jobs:
      - job1
      - job2:
          requires:
            - job1
      - job3:
          requires:
            - job1
      - job4:
          requires:
            - job2
            - job3
      - hold:
          type: approval
          requires:
            - job4
      - job5:
          requires:
            - hold
  nightly: #Scheduled workflow
    triggers:
      - schedule:
          cron: 10 13 * * *
          filters:
            branches:
              only:
                - workflow_configuration_examples
    jobs: #All jobs will be executed simultaneously
      - job1
      - job2
      - job3
      - job4