# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job1 Hello"
  job2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job2 Hello"
  job3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Job3 Hello"

workflows:
  version: 2
  workflow1:
    jobs:
      - job1
      - job2
      - job3
  workflow2:
    jobs:
      - job1
      - job2:
          requires:
            - job1
      - job3:
          requires:
            - job2

